version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/carsharing_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 228322
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: carsharing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 228322
    ports:
      - "5432:5432"